### ISSUE TITLE
RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1).

### ISSUE THREAD

**Issue by choucaicai** [VideoCrafter/VideoCrafter#90]
When running ```sh scripts/run_text2video.sh```, an error occurred.

```
[rank:0] batch-1 (1)x1 ...
Traceback (most recent call last):
  File "/media/mil/cc-code/VADER/VideoCrafter/scripts/evaluation/inference.py", line 137, in <module>
    run_inference(args, gpu_num, rank)
  File "/media/mil/cc-code/VADER/VideoCrafter/scripts/evaluation/inference.py", line 107, in run_inference
    text_emb = model.get_learned_conditioning(prompts)
  File "/media/mil/cc-code/VADER/VideoCrafter/scripts/evaluation/../../lvdm/models/ddpm3d.py", line 448, in get_learned_conditioning
    c = self.cond_stage_model.encode(c)
  File "/media/mil/cc-code/VADER/VideoCrafter/scripts/evaluation/../../lvdm/modules/encoders/condition.py", line 235, in encode
    return self(text)
  File "/home/mil/anaconda3/envs/vdiff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mil/anaconda3/envs/vdiff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/mil/cc-code/VADER/VideoCrafter/scripts/evaluation/../../lvdm/modules/encoders/condition.py", line 212, in forward
    z = self.encode_with_transformer(tokens.to(self.device))
  File "/media/mil/cc-code/VADER/VideoCrafter/scripts/evaluation/../../lvdm/modules/encoders/condition.py", line 219, in encode_with_transformer
    x = self.text_transformer_forward(x, attn_mask=self.model.attn_mask)
  File "/media/mil/cc-code/VADER/VideoCrafter/scripts/evaluation/../../lvdm/modules/encoders/condition.py", line 231, in text_transformer_forward
    x = r(x, attn_mask=attn_mask)
  File "/home/mil/anaconda3/envs/vdiff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mil/anaconda3/envs/vdiff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mil/anaconda3/envs/vdiff/lib/python3.10/site-packages/open_clip/transformer.py", line 263, in forward
    x = q_x + self.ls_1(self.attention(q_x=self.ln_1(q_x), k_x=k_x, v_x=v_x, attn_mask=attn_mask))
  File "/home/mil/anaconda3/envs/vdiff/lib/python3.10/site-packages/open_clip/transformer.py", line 250, in attention
    return self.attn(
  File "/home/mil/anaconda3/envs/vdiff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mil/anaconda3/envs/vdiff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mil/anaconda3/envs/vdiff/lib/python3.10/site-packages/torch/nn/modules/activation.py", line 1275, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "/home/mil/anaconda3/envs/vdiff/lib/python3.10/site-packages/torch/nn/functional.py", line 5439, in multi_head_attention_forward
    raise RuntimeError(f"The shape of the 2D attn_mask is {attn_mask.shape}, but should be {correct_2d_size}.")
RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1).

```

**Comment by jiachunp** [comment]
try open_clip_torch==2.22.0, I can run it under this version
